export const ADDCART_REQUEST = "ADDCART_REQUEST";
export const ADDCART_SUCCESS = "ADDCART_SUCCESS";
export const ADDCART_FAILURE = "ADDCART_FAILURE";

export const GETCART_REQUEST = "GETCART_REQUEST";
export const GETCART_SUCCESS = "GETCART_SUCCESS";
export const GETCART_FAILURE = "GETCART_FAILURE";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILURE = "GET_ORDER_FAILURE";
