export const FETCH_CANTEENS_REQUEST = "FETCH_CANTEENS_REQUEST";
export const FETCH_CANTEENS_SUCCESS = "FETCH_CANTEENS_SUCCESS";
export const FETCH_CANTEENS_FAILURE = "FETCH_CANTEENS_FAILURE";

export const FETCH_CANTEEN_REQUEST_BY_ID = "FETCH_CANTEENS_REQUEST_BY_ID";
export const FETCH_CANTEEN_SUCCESS_BY_ID = "FETCH_CANTEENS_SUCCESS_BY_ID";
export const FETCH_CANTEEN_FAILURE_BY_ID = "FETCH_CANTEENS_FAILURE_BY_ID";
